GCI-2158 Implement basket endpoints
companieshouse/api-sdk-node pull request #425
Opened 2022-07-19 11:59 UTC by cgregoryCH

- Implement service methods to call orders api basket endpoints:
- Remove basket item
- Get basket links

- Add basket types for sdk users

[GCI-2158](https://companieshouse.atlassian.net/browse/GCI-2158)

2022-07-19 12:22 UTC, kinpang-CH approved these changes

2022-07-19 12:54 UTC, dlgroves-ch requested changes

2022-07-19 12:54 UTC, dlgroves-ch commented on src/services/order/basket/service.ts
> +        resource.resource = Mapping.camelCaseKeys<BasketLinks>(body, BasketService.EXCLUDED_FIELDS_FULL_BASKET);
Exclusions not required as the getBasketLinks service endpoint does not embed items:

```javascript
resource.resource = Mapping.camelCaseKeys<BasketLinks>(body);
```

2022-07-21 13:20 UTC, dlgroves-ch approved these changes

2022-07-22 09:32 UTC, merged