CC-605: Do not drop additional headers
companieshouse/api-sdk-node pull request #593
Opened 2023-08-10 14:55 UTC by VaughanJackson123

* This work undoes a change made back in April that was recently found to result the SDK not propagating additional headers provided to its outgoing HTTP requests, as described in [the bug](https://companieshouse.atlassian.net/browse/CC-605).
* It also provides a couple of automated tests that hopefully should catch such issues should they arise again.
* The substantive change was tested with the `certificates.orders.web.ch.gov.uk` node application [manually in Tilt](https://companieshouse.atlassian.net/browse/CC-605?focusedCommentId=220161) earlier today.

2023-08-10 16:36 UTC, mwejuli-ch requested changes

2023-08-10 16:36 UTC, mwejuli-ch commented on src/http/request-client.ts
> +                    ...this.headers,
might be a best to keep the old functionality alongside the new change you're making i.e. ensuring that if `this.headers` and `additionalOptions.headers` do not have the `accept` and `content-type` headers, we use those in the current implementation as the default

2023-08-10 16:36 UTC, mwejuli-ch commented on test/http/request-client.spec.ts
> +import nock = require("nock");
i'm not against using `nock` here but perhaps u might first want to consider re-using the existing patterns for your new tests? have a look at how the existing tests solve a similar issue.. it might be the case that we still need `nock` for this but only if the existing patterns are insufficient or non-beneficial.

2023-08-10 16:37 UTC, VaughanJackson123 commented on src/http/request-client.ts
> +                    ...this.headers,
I'll look into this, thanks.

2023-08-10 16:38 UTC, VaughanJackson123 commented on test/http/request-client.spec.ts
> +import nock = require("nock");
I'll look into this tomorrow as we discussed Moses.

2023-08-14 15:53 UTC, mwejuli-ch approved these changes

2023-08-14 15:58 UTC, VaughanJackson123 commented on test/http/request-client.spec.ts
> +import nock = require("nock");
* We looked into the possibility of using sinon to mock the outgoing request and match against its headers but met with little success.
* After further discussions we have decided that using nock as we have done here to verify the headers on outgoing (mocked out) HTTP requests should be an acceptable approach as the requests are completely mocked out by nock and no external processes are involved in such tests.

2023-08-14 16:01 UTC, merged