Add unit tests for psc-verification-link service
companieshouse/api-sdk-node pull request #660
Opened 2024-04-18 14:52 UTC by hepsimo

- make PscVerification properties optional:
  - psc_appointment_id
  - verification_details
- add nyc  for test coverage reporting
- add 'test:coverage' npm script

2024-04-19 15:31 UTC, mwejuli-ch requested changes

2024-04-19 15:31 UTC, mwejuli-ch commented on package.json
> +    "nyc": {
Do we need all of the `nyc` config in package.json?

We could have, in the `scripts` stanza, something like:

```
"test:coverage": "nyc --check-coverage --reporter=text-summary npm run test",
"coverage:report": "nyc --reporter=lcov --reporter=text npm run test",
```
Perhaps I could've missed something?

2024-04-22 09:52 UTC, hepsimo commented on package.json
> +    "nyc": {
Good idea, i'll change the scripts stanza. I did need to add the nyc package and the config was added by npm i guess

2024-04-22 10:07 UTC, mwejuli-ch commented on package.json
> +    "nyc": {
Great.. You can now remove the `nyc` entry at the bottom

2024-04-22 13:13 UTC, merged